config_file: "../sampled_supervision_basic_config.yml"
exp_name: "7 regions v0"
features_path: features/cholec80/cholec80-imagenet001/
timestamp_path: sampled_supervision/labels/cholec80_7regions.npy
confidence_weight: 0