config_file: "../sampled_supervision_basic_config.yml"
exp_name: "model missing 0.2 v0"
features_path: features/cholec80/cholec80-imagenet001/
timestamp_path: data/cholec80/groundTruth/cholec80_annotation_all_0.2_missing.npy
confidence_weight: 0
# casual_model: true