config_file: "../sampled_supervision_basic_config.yml"
exp_name: "model missing 0.2 v5"
timestamp_path: data/MultiBypass140/groundTruth/MultiBypass140_annotation_all_0.2_missing.npy
features_path: features/MultiBypass140/MultiBypass140-cholec004/
ctc_varient: "stc"
ctc_weight: 1
loss_weights: "ipw"
focal_loss: true
focal_gamma: 2
confidence_weight: 0.075
