config_file: "model_v5.yml"
exp_name: "model missing 0.2 additional_train_temp_0.25"
num_initial_epochs: 50
# ctc_start_epoch: 30
initial_labels_path: "results/cholec80/model missing 0.3 v5/split_1_certain/"
loss_weights: None
# focal_loss: False
confidence_weight: 0
entropy_weight: 0
ctc_weight: 0